spring.application.name=feedbackwall
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=user
spring.datasource.password=password

# Performance
spring.threads.virtual.enabled=true

# Development Speed (Auto-reload Thymeleaf templates)
spring.thymeleaf.cache=false
spring.sql.init.mode=always